apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaling-demo
  name: demo
  namespace: scaling-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaling-demo
  template:
    metadata:
      labels:
        app: scaling-demo
    spec:
      containers:
      - image: johndohoney/aks-scaling-demo:v1
        name: aks-auto-scaler-demo
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /status/health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
          requests:
            memory: "64Mi"
